### PR TITLE
Create Lambda Function -WOTD

### PR DESCRIPTION
**Pull request by sarahmau**
This is not totally set up. Just what I have so far :)

### CODE REVIEW

**Comment by fromcj** [comment]
We should probably work out a requirements doc before we start working on actual code

**Comment by sarahmau** [comment]
Good call Cj :D

**Comment by kurron** [comment]
@sarahmau a good practice to have is to have automated test to go along with the code.  I suppose now that we've selected Python as the language we should also select the build and testing tools.

**Comment by fromcj** [comment]
Closing old PR

**Pull request closed without merging**
